package id.ac.tazkia.smilemahasiswa.entity;

public enum StatusRecord {
    AKTIF, PRAAKTIF, NONAKTIF, HAPUS, Y, N, TANGGUHKAN, DITAGIH_SELANJUTNYA, LUNAS, BELUM_LUNAS, GANJIL, GENAP, PENDEK,UTS,UAS,KRS,SKRIPSI, SEMPRO, STUDI_KELAYAKAN,DONE,UNDONE, PREVIEW, CUTI
}
